### ISSUE TITLE
remove lock on exit

### ISSUE THREAD

**Issue by ORESoftware** [TheDeveloper/warlock#10]
Hi,

How can users of this library remove the lock upon exit? In some cases, I am running a script and I kill the script before it completes and my guess is that Warlock does not release the Redis lock. How can we be guaranteed to be able to put a lock on a given Redis key?

**Comment by TheDeveloper** [comment]
For this you'll want some kind of shutdown procedure so that when the script is killed, you finish the work that's pending and release the locks before the process exits.

See https://nodejs.org/api/process.html#process_signal_events

**Comment by ORESoftware** [comment]
Cool, that looks right. I think you should add this functionality into warlock; might as well, since you will be releasing the same key as you locked on.

**Comment by ORESoftware** [comment]
you could simply have it passed as a boolean value - unlock upon exit, yes or no

**Comment by ORESoftware** [comment]
this would be ideal

**Comment by TheDeveloper** [comment]
I'd be reluctant to do this because the app should have control over when the process exits, and to do this reliably warlock would have to block exit until Redis commands have completed.

It should be fairly easy to implement this in the app itself - keep an object of all locks in place and unlock them all on process exit if needed.

**Comment by ORESoftware** [comment]
hmmm, it's your module :) given what you just said, just make the default false, but if true is passed then your module has functionality to deal with it

**Comment by the1mills** [comment]
Also, instead of having a shutdown hook to remove the lock upon exit, is there a way, at the top of a program, to remove all locks on given keys? In your codebase now, the unlock() only exists if we call lock() first...but why can't we do a hard unlock() on a key without first calling lock()? I want a hard unlock(), is this possible?

**Comment by TheDeveloper** [comment]
@the1mills the locks are strict mutex, such that only the process that owns the lock can unset it. Depending on your use case, you could simply `redis.del(lockKey)` to release the lock without calling `warlock.lock()` first, but consider the following:

I think in both these cases, adding this functionality is a bad substitute for managing the locks properly in your app / use case.

It takes a little more thought, as to when exactly locks are set / released, especially in cases of shutdown / crashes, but it means that you deal with those cases in the safest way.

**Comment by ORESoftware** [comment]
hmmm, I don't agree!!!  if your process with PID 5555 dies, before unlocking the lock. then when you start a new process it won't work.

you must provide a reliable way to unlock the lock from a new process, even if it is to just delete the Redis key...

**Comment by TheDeveloper** [comment]
That's why it's recommended to set a ttl on every lock so that if the
process fails to unlock for any reason, it will eventually expire.

Also, it's still possible to use domains (and in future, AsyncWrap) to try
to unlock when an uncaught exception or exit occurs.

I still believe that it's the program's responsibility to manage when locks
are set and unset, and to deal with issues in the way that makes the most
sense for the application.

This module simply provides the locking primitives, and shouldn't try to
make assumptions about the locking intent of the parent application -
because rarely one size fits all here.

**Comment by ORESoftware** [comment]
you make good points
