### ISSUE TITLE
Force unlock

### ISSUE THREAD

**Issue by BrandonCopley** [TheDeveloper/warlock#15]
I would like to be able to force an unlock even if I don't know the id, is this possible?

**Comment by TheDeveloper** [comment]
Hi Brandon,

By design only the owner of the lock should be able to release it. I'm dubious that any other pattern is appropriate but I would like to hear why you feel this is necessary?

**Comment by BrandonCopley** [comment]
One problem I have is rebooting the server. On reboot the function is still
locked out, even though it's clearly not running.

On Monday, November 9, 2015, Geoff Wagstaff <notifications@github.com>
wrote:

> Hi Brandon,
>
> By design only the owner of the lock should be able to release it. I'm
> dubious that any other pattern is appropriate but I would like to hear why
> you feel this is necessary?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TheDeveloper/warlock/issues/15#issuecomment-155054679>
> .
>


-- 
[image: Giftnix]

Brandon Copley

Founder & CEO

t: 512.784.6060

e: copley.brandon@gmail.com

**Comment by TheDeveloper** [comment]
Ideally, your process would have some sort of shut down procedure where it finishes its work and releases the lock before exiting. I appreciate that this isn't always possible though.

Other than that, you can rely on the lock timeouts to release the lock so that when your app boots up again it can eventually obtain the lock.

**Comment by calibr** [comment]
Hello, I think it would be usefull feature for some cases if warlock returns the lock id in .lock callback. For example, In our system we are going to develop such workflow for collaborative text editor:
- User starts to edit a text and client sends to server command(http request or websocket request) to lock the text and receives the lock id
- Another user can't edit the same text at the same time with first user, because it's exclusively locked
- When first user finishes editing client sends command to unlock it and from that moment second user becomes able to edit the text

So for this flow the lock TTL depends on how long first user will interact with text via client GUI and when it finishes we need to release the lock immediately.

**Comment by TheDeveloper** [comment]
Hi @calibr, thank you for detailing that use case. It makes sense to know the lock ID there. Perhaps it could be set as a property of the unlock function, or passed as an additional argument to the lock callback.

**Comment by calibr** [comment]
thanks, I'm going to submit a pull request for this in few days

**Comment by TheDeveloper** [comment]
@calibr that would be much appreciated :+1:
